config/routes.rb
HebprojApp::Application.routes.draw do

  devise_for :users
  get "words/new"
  get "words/edit"
  resources :lessons 
  resources :examples 
  resources :words  
  root  'static_pages#home' 
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/lesson-index/:id/' => 'lessons#lesson_index',via: 'get', as: :lesson_index
  
  
  

  

end

app/models/example.rb
class Example < ActiveRecord::Base  
  belongs_to :lesson
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :examples, dependent: :destroy
  has_many :words, dependent: :destroy
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :lesson
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  
  def new
    self.current_lesson
    @languages = HebprojApp::Application::LANGUAGES
    @example = Example.new
  end

  def create
    @example = self.current_lesson.examples.build(example_params)
    if @example.save
      flash[:success] = "good you created an example!"
      redirect_to current_lesson
    else
      flash.now[:error] = 'Invalid example parameters'
      render 'new'
    end
  end

  def edit 
    self.current_lesson
    @languages = HebprojApp::Application::LANGUAGES
    @example = Example.find_by(params[:id])  
  end

  def update
    @example = Example.find(params[:id])
    if @example.update_attributes(example_params)
      flash[:success] = "Example updated"
      redirect_to @example.lesson
    else
      render 'edit'
    end 
  end


  def destroy
    examp_lesson = Example.find(params[:id]).lesson
    Example.find(params[:id]).destroy
    flash[:success] = "Lesson destroyed."
    redirect_to examp_lesson
  end

  
  def current_lesson
    @current_lesson = Lesson.find_by(params[:lesson_id])
  end


    private
 
  def example_params
    params.require(:example).permit(:hebrew_sentence, :ivrit_sentence, :english_sentence,
                                    :french_sentence, :spanish_sentence, :russian_sentence,
                                    :dutch_sentence, :german_sentence,
                                    :hebrew_note, :ivrit_note, :english_note,
                                    :french_note, :spanish_note, :russian_note,
                                    :dutch_note, :german_note)
  end                                                                   
end                      

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
   NUMBER_OF_CLASSES=5
 
  
  def new
    @lesson = Lesson.new
    @lesson.class_num = params[:class_num]
    @lesson.sub_class_num = params[:sub_class_num]
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      flash[:success] = "good you created a lesson!"
      redirect_to @lesson
    else
      flash.now[:error] = 'Invalid lesson parameters'
      render 'new'
    end
  end

  def edit
    @lesson = Lesson.find_by(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update_attributes(lesson_params)
      flash[:success] = "Lesson updated"
      redirect_to @lesson
    else
      render 'edit'
    end 
  end

  def show
    @lesson = Lesson.find_by(params[:id])
    @languages = HebprojApp::Application::LANGUAGES
  end
  
  def index
    @number_of_classes = NUMBER_OF_CLASSES
  end

  def lesson_index
    @lessons = Lesson.where('class_num' => params[:id])
    @last_lesson = 1
    @class_number =  params[:id]
  end

  def destroy
    Lesson.find(params[:id]).destroy
    flash[:success] = "Lesson destroyed."
    redirect_to lessons_url
  end

    private

  def lesson_params
    params.require(:lesson).permit(:name, :note, :class_num,
                                   :sub_class_num, :lesson_num)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
def new
    self.current_lesson
    @languages = HebprojApp::Application::LANGUAGES
    @word = Word.new
  end

  def create
    @word = self.current_lesson.words.build(word_params)
    if @word.save
      flash[:success] = "good you created a word!"
      redirect_to current_lesson
    else
      flash.now[:error] = 'Invalid word parameters'
      render 'new'
    end
  end

  def edit 
    self.current_lesson
    @languages = HebprojApp::Application::LANGUAGES
    @word = Word.find_by(params[:id])  
  end

  def update
    @word = Word.find(params[:id])
    if @word.update_attributes(word_params)
      flash[:success] = "Word updated"
      redirect_to @word.lesson
    else
      render 'edit'
    end 
  end


  def destroy
    word_lesson = Word.find(params[:id]).lesson
    Word.find(params[:id]).destroy
    flash[:success] = "Word destroyed."
    redirect_to word_lesson
  end

  
  def current_lesson
    @current_lesson = Lesson.find_by(params[:lesson_id])
  end


    private
 
  def word_params
    params.require(:word).permit(:hebrew, :ivrit, :english,
                                    :french, :spanish, :russian,
                                    :dutch, :german, :verb, :shoresh,
                                    :shoresh_type, :main_word,
                                    :order_num)
  end                                                                   
end    

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Learn Hebrew Project"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/examples/_example_form.html.erb
<%= form_for(@example) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>   
  <input name="lesson_id" type="hidden" value= <%= @current_lesson.id%> />
  <%= @current_lesson.id%>
    <%= f.label :verb %>
    <%= f.text_field :verb %>
    <%= f.label :shoresh %>
    <%= f.text_field :shoresh %>
    <%= f.label :shoresh_type %>
    <%= f.text_field :shoresh_type%>
    <%= f.label :order_num %>
    <%= f.text_field :order_num%>

  <% @languages.each do |lan| %>
    <%lan_sen="#{lan}_sentence" %>
    <%= f.label lan_sen.to_sym %>
    <%= f.text_field lan_sen.to_sym %>
  <% end %>
    <% @languages.each do |lan| %>
    <%lan_note="#{lan}_note" %>
    <%= f.label lan_note.to_sym %>
    <%= f.text_field lan_note.to_sym %>
  <% end %>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/examples/edit.html.erb
<% provide(:title, "Edit example") %>
<h1>Update example</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'example_form' %>  
  </div>
</div>

app/views/examples/new.html.erb
<% provide(:title, 'Create example') %>
<h1>Create Example</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'example_form' %>  

  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    learning hebrew
    by Yaron Einhorn
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "heb camp", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "lessons", lessons_path %></li>
          <li><%= link_to "categories", '#' %></li>
          <% if user_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.email %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", '#' %></li>
                <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/lessons/_lesson_form.html.erb
<%= form_for(@lesson) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>  
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :class_num %>
      <%= f.number_field :class_num %>

      <%= f.label :sub_class_num %>
      <%= f.number_field :sub_class_num %>

      <%= f.label :lesson_num %>
      <%= f.number_field :lesson_num %>

      <%= f.label :note %>
      <%= f.text_area :note %>
      
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
    <% end %>

app/views/lessons/edit.html.erb
<% provide(:title, "Edit lesson") %>
<h1>Update lesson</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'lesson_form' %>  
  </div>
</div>

app/views/lessons/index.html.erb
<% provide(:title, 'All Lessons') %>
<h1>All lessons</h1>

<ul class="users">
  <% (1..@number_of_classes).each do |i| %>
    <li>
    <%= link_to "class number #{i} ",lesson_index_path(i)%>
    
    </li>
  <% end %>
</ul>

app/views/lessons/lesson_index.html.erb
<% provide(:title, 'class index') %>
<h1>Class number <%= @class_number %> </h1>

<ul class="users">
  <% if !@lessons.nil? %>
    <%  @lessons.each do |lesson| %>
      <li>
      <%= link_to "#{lesson.class_num}.#{lesson.sub_class_num} #{lesson.name}  ",lesson_path(lesson.lesson_num)%>
      <%= link_to "edit lesson",edit_lesson_path(lesson) %>,
      <%= link_to "delete", lesson, method: :delete,
      data: { confirm: "You sure?" } %>
        <%= @last_lesson=lesson.sub_class_num + 1 %>
      </li>

    <% end %>
  <% else %>
    <li> no lessons yet </li>
  <% end %>
  <li>   <%= link_to "create new lesson",new_lesson_path(:class_num => @class_number,
    :sub_class_num => @last_lesson) %>
  </li>

</ul>

app/views/lessons/new.html.erb
<% provide(:title, 'Create Lesson') %>
<h1>Create Lesson</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'lesson_form' %>  

  </div>
</div>

app/views/lessons/show.html.erb
<h1> <%= @lesson.class_num %>.<%= @lesson.sub_class_num %> <%= @lesson.name %></h1>
<div class="center-video">
<iframe width="560" height="315" src= "https://www.youtube.com/embed/6E2hYDIFDIU" frameborder="1" allowfullscreen></iframe>
</div>
<% example_number=1 %>
<% word_number=1 %>
<% if !@lesson.words.nil? %>
  <div class="accordion" id="accordion-words">
  <%  @lesson.words.each do |word| %>
    <% collapse_num="collapse_#{word_number}" %>
    <% href_collapse="#collapse_#{word_number}" %>

      <div class="accordion-group">
        <div class="accordion-heading">
          <ul class="rlist"><li>  
            <a class="accordion-toggle" data-toggle="collapse" data-target=#<%=collapse_num%> href=<%=href_collapse%>>
               <%=word.hebrew %> <%= link_to "edit word",edit_word_path(word) %>,
               <%= link_to "delete word", word, method: :delete,
               data: { confirm: "You sure?" } %>
              </a>
          </li></ul> 
        </div>
        <% if word_number==1 %>
          <div id=<%=collapse_num%> class="collapse in">
        <% else %>
           <div id=<%=collapse_num%> class="collapse">
        <% end %>

          <div class="accordion-inner">
            <ul class="rlist">  
            <% @languages.each do |lan| %> 
              <%lan_word="#{lan}" %>        
               <li><%=lan%>:  <%=word.read_attribute(lan_word) %>  </li>
             <% end %>
             </ul>
          </div>
        </div>
      </div>
       <% word_number=word_number+1 %>
    <% end %>    
    </div>

 <% else %>
    <ul class="rlist">           
      <li> no lessons yet </li>
    </ul>

  <% end %>  
   <ul class="rlist">             
  <li>  <%= link_to "create new word",new_word_path(:lesson_id => @lesson.id) %></li>
</ul>


  <% if !@lesson.examples.nil? %>
    <h3> Examples </h3>
    <div class="accordion" id="accordion-examples">    
      <%  @lesson.examples.each do |example| %>
        <% example_number=example_number+1 %>
        <% collapse_num="collapse2_#{example_number}" %>
        <% href_collapse="#collapse2_#{example_number}" %>
        <div class="accordion-group">
          <div class="accordion-heading">
            <ul class="rlist"><li> 
              <a class="accordion-toggle" data-toggle="collapse" data-target=#<%=collapse_num%> href=<%=href_collapse%>>
                <%=example.hebrew_sentence %> <%= link_to "edit example",edit_example_path(example) %>,
                <%= link_to "delete exampke", example, method: :delete,
                data: { confirm: "You sure?" } %>
              </a>
            </li></ul>
          </div>
          <div id=<%=collapse_num%> class="collapse">
            <div class="accordion-inner">
              <ul class="rlist">      
                <% @languages.each do |lan| %>    
                  <%lan_sen="#{lan}_sentence" %>
                  <li><%=lan%>:  <%=example.read_attribute(lan_sen) %>  </li>
                 <% end %>
              </ul>
            </div>
          </div>
        </div>
       <% example_number=example_number+1 %>
    <% end %>    
    </div>
  <% else %>
    <ul class="rlist">           
      <li> no lessons yet </li>
    </ul>
  <% end %>   
   <ul class="rlist">             
     <li>  <%= link_to "create new example",new_example_path(:lesson_id => @lesson.id) %></li>
  </ul>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Hebrew Project</h1>

  <h2>
    Singnig up for free will help you track your progress, taking notes
    and other very usefull options.
  </h2>

  <%= link_to "Sign up now!", new_user_registration_path,
    class: "btn btn-large btn-primary" %>

    <h2>
      Or you can just go straight to <%= link_to 'class', lessons_path %> and practice
    </h2>


</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/words/_word_form.html.erb
<%= form_for(@word) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>   
  <input name="lesson_id" type="hidden" value= <%= @current_lesson.id%> />
  <%= @current_lesson.id%>
  <% @languages.each do |lan| %>
    <%lan_word="#{lan}" %>
    <%= f.label lan_word.to_sym %>
    <%= f.text_field lan_word.to_sym %>
  <% end %>
  <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/words/edit.html.erb
<% provide(:title, "Edit word") %>
<h1>Update word</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'word_form' %>  
  </div>
</div>

app/views/words/new.html.erb
<% provide(:title, 'Create example') %>
<h1>Create Word</h1>

<div class="row">
  <div class="span6 offset3">
    <%= render 'word_form' %>  

  </div>
</div>